[package]
name = "lingua_rs_rb"
version = "0.1.0"
edition = "2021"
authors = ["OrfeasZ <orfeaz@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
lingua = "1.7.1"
